In [1]:
import numpy as np

## Count the unique values in a row

In [4]:
arr = np.random.randint(0, 10, size=(9,12))
print(arr)

[[9 5 5 5 1 1 6 1 9 0 9 0]
 [1 4 8 1 0 2 7 6 1 1 9 7]
 [4 1 6 5 2 2 9 6 5 3 9 6]
 [4 7 5 0 0 9 6 1 8 4 5 0]
 [8 2 2 9 0 1 5 7 4 9 7 9]
 [7 3 2 0 1 9 5 2 2 2 2 5]
 [8 2 6 4 1 8 8 6 4 0 2 1]
 [5 7 0 9 5 9 0 9 8 2 5 1]
 [0 5 6 8 7 9 3 2 2 2 8 8]]


In [6]:
#(m, n) where m is the number of rows and n is the number of columns
print(arr.shape)

(9, 12)


In [23]:
print(arr[:2])

[[9 5 5 5 1 1 6 1 9 0 9 0]
 [1 4 8 1 0 2 7 6 1 1 9 7]]


In [7]:
def count_unique(ar):
    return len(np.unique(ar))

In [47]:
unique_values = [count_unique(i) for i in arr]
print(unique_values)

[5, 8, 7, 8, 8, 7, 6, 7, 8]


## Checkerboard arrays

### Create a numpy array of dimension (20,20) and fill it with a checkerboard pattern of 1's and 0's

In [46]:
checkers = np.zeros((20,20))
#from the 0th row to the last row in steps of 2 rows, from the 0th index to the last index in steps of 2
checkers[::2, ::2]=1
#from the 1st row to the last row in steps of 2 rows, from the 1st index to the last index in steps of 2
checkers[1: :2, 1: :2]=1
print(checkers)


[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.