In [4]:
import numpy as np

## Count the unique values in a row

In [39]:
arr = np.random.randint(0, 10, size=(9,12))
print(arr)

[[1 8 8 3 1 5 2 3 1 8 8 0]
 [1 4 2 3 8 2 9 0 3 1 4 9]
 [1 7 1 2 7 4 1 9 0 2 8 3]
 [9 7 4 6 1 9 2 3 8 9 5 2]
 [4 8 2 2 6 5 6 2 1 3 5 1]
 [8 1 1 2 6 7 0 1 1 0 5 4]
 [8 4 4 4 6 2 5 3 4 9 4 9]
 [6 3 1 8 1 8 0 2 6 0 7 6]
 [4 8 6 9 0 2 4 1 0 0 2 6]]


In [40]:
#(m, n) where m is the number of rows and n is the number of columns
print(arr.shape)

(9, 12)


In [41]:
def count_unique(arr):
    return len(np.unique(arr))

In [47]:
unique_values = [count_unique(i) for i in arr]
print(unique_values)

[6, 7, 8, 9, 7, 8, 7, 7, 7]


#### Return Counts

In [54]:
def unique_count(arr):
    unique_values, occurence_count = np.unique(arr, return_counts=True)
    count = len(unique_values)
    return [unique_values, occurence_count, count]
        
unique_values = [unique_count(i) for i in arr]
print(unique_values)

[[array([0, 1, 2, 3, 5, 8]), array([1, 3, 1, 2, 1, 4]), 6], [array([0, 1, 2, 3, 4, 8, 9]), array([1, 2, 2, 2, 2, 1, 2]), 7], [array([0, 1, 2, 3, 4, 7, 8, 9]), array([1, 3, 2, 1, 1, 2, 1, 1]), 8], [array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 1, 1, 1, 1, 1, 1, 3]), 9], [array([1, 2, 3, 4, 5, 6, 8]), array([2, 3, 1, 1, 2, 2, 1]), 7], [array([0, 1, 2, 4, 5, 6, 7, 8]), array([2, 4, 1, 1, 1, 1, 1, 1]), 8], [array([2, 3, 4, 5, 6, 8, 9]), array([1, 1, 5, 1, 1, 1, 2]), 7], [array([0, 1, 2, 3, 6, 7, 8]), array([2, 2, 1, 1, 3, 1, 2]), 7], [array([0, 1, 2, 4, 6, 8, 9]), array([3, 1, 2, 2, 2, 1, 1]), 7]]


## Checkerboard arrays

- Create a numpy array of dimension (20,20) and fill it with a checkerboard pattern of 1's and 0's

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
#sliced
print(x[1:4])
#sliced in steps
print(x[1:6:2])

[2 3 4]
[2 4 6]


In [10]:
checkers = np.zeros((20,20))
#from the 0th row to the last row in steps of 2 rows, from the 0th index to the last index in steps of 2
checkers[::2, ::2]=1
#from the 1st row to the last row in steps of 2 rows, from the 1st index to the last index in steps of 2
checkers[1: :2, 1: :2]=1
print(checkers)

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.

## Broadcasting
- create a random matrix of binary values (0, 1)
- Create a vector with as many rows as the matrix containing random positive integers between 1 and 5
- Add the vector to every column using broadcasting
- Create a new matrix by multiplying the columns of the original by the vector
- Create a new matrix by multiplying every element by a scalar value



In [32]:
#matrix of random binary values
import random
rows = random.randint(3, 13)
columns = random.randint(3,13)
random_matrix = np.random.randint(0,2, size=(rows,columns))
print(random_matrix)


[[0 1 0 0 1 0 1]
 [1 0 1 1 1 1 0]
 [1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 0 0 1]
 [0 1 0 1 0 0 0]
 [1 0 0 0 0 1 1]
 [0 0 1 0 1 0 1]
 [1 1 1 0 1 1 1]]


In [33]:
print(random_matrix.shape)

(10, 7)


In [35]:
bc_vector = np.random.randint(1,5, size=(1, columns))[0]
print(bc_vector)

[2 4 2 4 1 1 1]


In [36]:
bc_matrix = random_matrix + bc_vector
print(bc_matrix)


[[2 5 2 4 2 1 2]
 [3 4 3 5 2 2 1]
 [3 5 2 4 1 1 1]
 [3 5 3 5 2 2 1]
 [2 4 2 4 1 1 1]
 [2 4 3 5 1 1 2]
 [2 5 2 5 1 1 1]
 [3 4 2 4 1 2 2]
 [2 4 3 4 2 1 2]
 [3 5 3 4 2 2 2]]


In [37]:
multiplied_matrix = bc_matrix * bc_vector
print(multiplied_matrix)

[[ 4 20  4 16  2  1  2]
 [ 6 16  6 20  2  2  1]
 [ 6 20  4 16  1  1  1]
 [ 6 20  6 20  2  2  1]
 [ 4 16  4 16  1  1  1]
 [ 4 16  6 20  1  1  2]
 [ 4 20  4 20  1  1  1]
 [ 6 16  4 16  1  2  2]
 [ 4 16  6 16  2  1  2]
 [ 6 20  6 16  2  2  2]]


In [38]:
scalar = 3
multiplied_matrix *= scalar
print(multiplied_matrix)

[[12 60 12 48  6  3  6]
 [18 48 18 60  6  6  3]
 [18 60 12 48  3  3  3]
 [18 60 18 60  6  6  3]
 [12 48 12 48  3  3  3]
 [12 48 18 60  3  3  6]
 [12 60 12 60  3  3  3]
 [18 48 12 48  3  6  6]
 [12 48 18 48  6  3  6]
 [18 60 18 48  6  6  6]]


## Fancy Indexing
- Look at the numpy docs to explore all the ways which you can use numpy to generate tensors/matrices/arrays of random numbers
- Create a matrix of random numbers with 4 rows and 6 columns
- Index the element on the 3rd row, 2nd column
- Index all the even rows
- Index the elements on even rows and odd columns
- Index the elements along the diagonal

In [57]:
rng = np.random.default_rng()
arr = rng.integers(2, size=10)
print(arr)

[1 1 1 0 1 0 0 1 0 0]


In [61]:
mat = rng.random((2,3))
print(mat)

[[0.69537124 0.87857356 0.75678594]
 [0.32517498 0.16707181 0.45763821]]


In [62]:
ten = rng.random((2,3,2))
print(ten)

[[[0.07388641 0.47402905]
  [0.91586459 0.13476398]
  [0.69427255 0.25271321]]

 [[0.87816039 0.04744535]
  [0.29438863 0.78097607]
  [0.36565917 0.43072367]]]


In [64]:
A = np.random.randint(0,10, size = (4, 6))
print(A)

[[9 6 6 0 5 7]
 [3 6 6 6 6 8]
 [7 2 6 3 4 5]
 [6 6 0 7 9 4]]


In [72]:
#index third row second column
i = A[2,1]
print(i)

2


In [76]:
#index all even rows
i = A[:: 2]
print(i)

[[9 6 6 0 5 7]
 [7 2 6 3 4 5]]


In [78]:
#index all elements on even rows and odd columns
i = A[:: 2, 1::2]
print(i)

[[6 0 7]
 [2 3 5]]


In [79]:
#index the elements along the diagonal
i = A[(0,1,2,3), (0,1,2,3)]
print(i)

[9 6 6 7]


## Bordering an array

- Write a numpy program to add a border of zeros to the outside elements of an array of size (20,20)
- Can you do it with a 3D array of dimension (20,20,20)?
- Try the same with an array of dimension (20,40,10)

In [90]:
arr = np.random.randint(0,9, size=(20,20))
print(arr)

[[7 4 0 8 6 6 1 7 4 0 5 4 0 6 0 0 6 7 5 4]
 [5 8 1 4 5 7 4 5 5 0 8 1 0 5 8 4 1 8 5 5]
 [2 1 7 2 6 7 4 5 7 1 0 7 5 0 5 4 7 6 8 7]
 [6 6 4 0 0 4 0 4 5 6 2 2 1 6 5 6 3 0 0 0]
 [2 8 6 5 0 6 7 2 0 6 1 4 0 7 6 4 4 6 7 4]
 [4 6 4 4 5 2 4 3 0 0 7 2 8 3 8 2 4 2 8 7]
 [5 2 5 0 2 0 2 3 2 5 4 3 7 0 4 7 3 1 4 7]
 [0 0 3 7 8 0 6 6 8 0 8 7 2 0 7 8 7 0 3 2]
 [8 5 6 4 1 7 6 6 1 3 2 7 1 8 2 4 0 2 2 5]
 [1 1 2 2 5 3 8 0 2 6 4 0 3 3 5 7 5 2 1 3]
 [0 8 3 6 8 6 1 8 3 3 1 8 2 7 4 8 5 5 2 4]
 [5 7 3 0 3 1 6 0 2 4 8 8 1 0 3 5 8 3 2 8]
 [6 4 5 6 5 7 4 5 6 3 2 3 0 6 1 2 0 3 4 4]
 [7 0 2 1 5 6 1 1 0 2 7 4 5 4 5 3 1 1 8 6]
 [6 4 5 6 1 4 6 6 3 3 6 7 7 5 5 8 2 1 3 3]
 [5 4 4 7 8 6 6 5 1 1 6 3 3 6 6 6 5 0 4 5]
 [1 4 1 5 2 0 7 4 7 1 0 5 8 5 7 5 2 2 3 7]
 [6 2 2 8 3 4 8 2 8 7 0 8 0 2 1 4 8 5 0 5]
 [4 0 2 2 8 6 1 3 3 7 1 6 0 7 3 5 4 5 3 0]
 [0 2 7 4 7 3 4 0 4 8 7 8 3 2 3 8 6 1 4 6]]


In [91]:
arr[:, [0, -1]] = arr[[0,-1]] = 0
print(arr)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 8 1 4 5 7 4 5 5 0 8 1 0 5 8 4 1 8 5 0]
 [0 1 7 2 6 7 4 5 7 1 0 7 5 0 5 4 7 6 8 0]
 [0 6 4 0 0 4 0 4 5 6 2 2 1 6 5 6 3 0 0 0]
 [0 8 6 5 0 6 7 2 0 6 1 4 0 7 6 4 4 6 7 0]
 [0 6 4 4 5 2 4 3 0 0 7 2 8 3 8 2 4 2 8 0]
 [0 2 5 0 2 0 2 3 2 5 4 3 7 0 4 7 3 1 4 0]
 [0 0 3 7 8 0 6 6 8 0 8 7 2 0 7 8 7 0 3 0]
 [0 5 6 4 1 7 6 6 1 3 2 7 1 8 2 4 0 2 2 0]
 [0 1 2 2 5 3 8 0 2 6 4 0 3 3 5 7 5 2 1 0]
 [0 8 3 6 8 6 1 8 3 3 1 8 2 7 4 8 5 5 2 0]
 [0 7 3 0 3 1 6 0 2 4 8 8 1 0 3 5 8 3 2 0]
 [0 4 5 6 5 7 4 5 6 3 2 3 0 6 1 2 0 3 4 0]
 [0 0 2 1 5 6 1 1 0 2 7 4 5 4 5 3 1 1 8 0]
 [0 4 5 6 1 4 6 6 3 3 6 7 7 5 5 8 2 1 3 0]
 [0 4 4 7 8 6 6 5 1 1 6 3 3 6 6 6 5 0 4 0]
 [0 4 1 5 2 0 7 4 7 1 0 5 8 5 7 5 2 2 3 0]
 [0 2 2 8 3 4 8 2 8 7 0 8 0 2 1 4 8 5 0 0]
 [0 0 2 2 8 6 1 3 3 7 1 6 0 7 3 5 4 5 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [109]:
arr = np.random.randint(0,9, size=(20,40,10))
print(arr[0])

[[1 1 8 3 2 0 0 0 4 5]
 [2 2 4 6 7 3 8 6 3 7]
 [2 4 3 1 5 4 8 2 1 0]
 [7 3 2 1 6 7 6 6 1 8]
 [7 8 7 3 1 5 4 6 6 0]
 [6 3 7 3 5 4 6 4 7 5]
 [5 2 8 6 6 5 5 8 0 4]
 [8 3 1 5 7 8 2 4 0 0]
 [4 7 1 7 5 0 8 6 4 4]
 [8 6 4 3 6 0 7 6 3 0]
 [3 4 8 7 3 6 3 4 4 0]
 [3 8 3 2 7 8 4 1 4 0]
 [3 7 8 1 7 6 7 3 4 1]
 [2 1 7 0 6 7 3 0 7 2]
 [5 5 5 6 7 4 2 5 6 5]
 [1 1 0 0 8 4 8 4 7 4]
 [3 6 2 2 1 2 0 2 5 3]
 [5 0 8 2 1 1 8 3 2 8]
 [2 6 0 1 4 6 6 7 1 0]
 [8 4 8 1 6 6 4 1 5 6]
 [8 4 0 0 7 5 8 3 3 8]
 [2 8 8 6 1 2 5 8 4 1]
 [5 1 4 4 1 4 5 2 5 5]
 [1 5 4 1 2 1 4 7 7 2]
 [5 4 1 7 2 0 5 6 1 2]
 [8 0 4 5 0 6 1 3 2 0]
 [2 1 3 2 2 7 7 3 1 2]
 [2 0 1 5 1 2 8 4 4 5]
 [7 6 8 7 5 3 2 1 5 1]
 [3 1 7 1 8 6 4 3 0 1]
 [3 2 3 6 7 2 3 2 7 3]
 [8 6 1 8 0 0 1 0 7 6]
 [6 3 6 3 4 1 8 3 1 6]
 [4 4 8 3 5 4 0 0 0 6]
 [7 3 3 1 7 4 3 0 3 8]
 [1 7 8 1 7 8 1 8 3 8]
 [0 7 1 0 0 7 4 0 7 5]
 [6 4 7 6 1 6 0 7 7 6]
 [1 6 8 1 1 7 3 3 1 1]
 [3 0 0 1 8 6 5 4 3 5]]


In [110]:
arr[:,:, [0, -1]] = arr[:,[0,-1]] = 0
print(arr)

[[[0 0 0 ... 0 0 0]
  [0 2 4 ... 6 3 0]
  [0 4 3 ... 2 1 0]
  ...
  [0 4 7 ... 7 7 0]
  [0 6 8 ... 3 1 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 6 1 ... 4 5 0]
  [0 7 0 ... 8 6 0]
  ...
  [0 6 8 ... 5 6 0]
  [0 5 1 ... 8 2 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 8 1 ... 1 3 0]
  [0 1 8 ... 3 5 0]
  ...
  [0 8 8 ... 4 8 0]
  [0 4 8 ... 0 5 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 6 3 ... 6 4 0]
  [0 2 1 ... 0 4 0]
  ...
  [0 8 5 ... 4 3 0]
  [0 4 1 ... 0 6 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 5 3 ... 4 6 0]
  [0 6 0 ... 8 7 0]
  ...
  [0 6 4 ... 4 3 0]
  [0 8 4 ... 8 6 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 2 3 ... 7 5 0]
  [0 5 7 ... 0 0 0]
  ...
  [0 6 2 ... 4 7 0]
  [0 6 6 ... 8 1 0]
  [0 0 0 ... 0 0 0]]]
